version: '3.4'

services:
  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: MutexDev
      POSTGRES_DB: mutex
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - mutex_default

  mutex-api:
    image: ${DOCKER_REGISTRY-}mutexapi
    build:
      context: .
      dockerfile: mutex-api/Dockerfile
    networks:
      - mutex_default

networks:
  mutex_default:

volumes:
  dbdata:
